### ISSUE TITLE
Rand number - incorrect

### ISSUE THREAD

**Issue by nothingto** [JamesGriffin/CHIP-8-Emulator#1]
The correct method on choosing a random number should be 0-255 (inclusive). `rand() % 0xFF` will not allow 255 to be inclusive. So the code should instead be `rand() % 0xFF + 1`
```
        case 0xC000:
            V[(opcode & 0x0F00) >> 8] = (rand() % 0xFF) & (opcode & 0x00FF);
            pc += 2;
            break;
```

**Comment by JamesGriffin** [comment]
Ah, good catch. Thanks :+1:
